name: تحديث ملف البث
on:
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق
  workflow_dispatch:       # تشغيل يدوي أيضًا

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: تحميل الكود
        uses: actions/checkout@v3

      - name: إعداد بايثون
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: تثبيت المكتبات
        run: pip install requests beautifulsoup4

      - name: تشغيل سكربت التحديث
        run: python update.py

      - name: رفع التحديث
        run: |
          git config --global user.name "match-bot"
          git config --global user.email "bot@example.com"
          git add latest.json
          git commit -m "تحديث البيانات" || echo "لا يوجد تغيير"
          git push
